
# Определяем список сервисов — services
# Эти сервисы будут частью нашего приложения
services:
  app: # Имя сервиса

    ports:
    - "8080:8080"
    command: make dev
      # Контекст для сборки образа,
      # в данном случае, текущая директория
#      context: .
      # Имя Docker-файла из которого будет собран образ
#      dockerfile: Dockerfile
      # Команда, которая будет выполнена после старта сервиса
#    command: make start
#    ports: # Проброс портов
#      - "8080:8080"
    # Перечисляем тома (volumes)
    # Они будут подключены к файловой системе сервиса
    # Например, все что находится в . мы увидим в директории /app
    #volumes:
      # Текущая директория пробрасывается в директорию /app внутри контейнера
      # Путь внутри контейнера (после двоеточия) обязательно должен быть абсолютным
    #  - "./app:/app"

