
# Определяем список сервисов — services
# Эти сервисы будут частью нашего приложения
services:

  app: # Имя сервиса
    build:
      # Контекст для сборки образа,
      # в данном случае, текущая директория
      context: .
      dockerfile: ./Dockerfile.production
    image: slavazhuck/devops-for-programmers-project-74
    command: make test
